/* Additional record code for System generated by the OpenModelica Compiler OpenModelica 1.20.0. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "System_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Prm__desc_added 1
const char* Prm__desc__fields[11] = {"ID","MyMagicNumber","W","N","A","B","C","D","F","G","T"};
struct record_description Prm__desc = {
  "Prm", /* package_record__X */
  "Prm", /* package.record_X */
  Prm__desc__fields
};

void Prm_construct_p(threadData_t *threadData, void* v_ths ) {
  Prm* ths = (Prm*)(v_ths);
  ths->_ID = ((modelica_integer) 1960447);
  ths->_MyMagicNumber = ((modelica_integer) 12);
  ths->_W = ((modelica_integer) 5);
  ths->_N = ((modelica_integer) 10);
  ths->_A = ((modelica_integer) 1);
  ths->_B = ((modelica_integer) 1);
  ths->_C = ((modelica_integer) 1);
  ths->_D = ((modelica_integer) 1);
  ths->_F = ((modelica_integer) 1);
  ths->_G = ((modelica_integer) 2);
  ths->_T = ((modelica_integer) 1);
}
// This function should eventually replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Prm omc_Prm(threadData_t *threadData , modelica_integer  in_ID, modelica_integer  in_MyMagicNumber, modelica_integer  in_W, modelica_integer  in_N, modelica_integer  in_A, modelica_integer  in_B, modelica_integer  in_C, modelica_integer  in_D, modelica_integer  in_F, modelica_integer  in_G, modelica_integer  in_T) {
  Prm dst;
  // TODO Improve me. No need to initialize the record members with defaults in Prm_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Prm_construct(threadData, dst);
  dst._ID =  in_ID;
  dst._MyMagicNumber =  in_MyMagicNumber;
  dst._W =  in_W;
  dst._N =  in_N;
  dst._A =  in_A;
  dst._B =  in_B;
  dst._C =  in_C;
  dst._D =  in_D;
  dst._F =  in_F;
  dst._G =  in_G;
  dst._T =  in_T;
  return dst;
}
*/

void Prm_copy_p(void* v_src, void* v_dst) {
  Prm* src = (Prm*)(v_src);
  Prm* dst = (Prm*)(v_dst);
  dst->_ID = src->_ID;
  dst->_MyMagicNumber = src->_MyMagicNumber;
  dst->_W = src->_W;
  dst->_N = src->_N;
  dst->_A = src->_A;
  dst->_B = src->_B;
  dst->_C = src->_C;
  dst->_D = src->_D;
  dst->_F = src->_F;
  dst->_G = src->_G;
  dst->_T = src->_T;
}

#ifdef __cplusplus
}
#endif

