/* Additional record code for System generated by the OpenModelica Compiler OpenModelica 1.20.0. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "System_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

